openapi: 3.0.3
info:
  title: OpenAI Agent with Qdrant Retrieval API
  description: API for interacting with the retrieval-enabled OpenAI agent
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/agent/query:
    post:
      summary: Submit a query to the retrieval-enabled agent
      description: Processes a user query by retrieving relevant context from Qdrant and generating a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/agent/health:
    get:
      summary: Health check for the agent service
      description: Checks if the agent service and its dependencies are operational
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's query text
          example: "What are the key principles of humanoid robotics?"
        options:
          type: object
          description: Additional options for the query
          properties:
            top_k:
              type: integer
              description: Number of chunks to retrieve from Qdrant
              minimum: 1
              maximum: 20
              default: 5
            similarity_threshold:
              type: number
              description: Minimum similarity score for retrieved chunks
              minimum: 0.0
              maximum: 1.0
              default: 0.5
            include_sources:
              type: boolean
              description: Whether to include source information in the response
              default: true

    AgentResponse:
      type: object
      required:
        - response
        - success
      properties:
        response:
          type: string
          description: The agent's generated response
          example: "The key principles of humanoid robotics include..."
        sources:
          type: array
          description: List of sources used to generate the response
          items:
            $ref: '#/components/schemas/RetrievedSource'
        success:
          type: boolean
          description: Whether the operation was successful
          example: true
        confidence:
          type: number
          description: Confidence score in the response (0.0 to 1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85

    RetrievedSource:
      type: object
      required:
        - content
        - score
        - metadata
      properties:
        content:
          type: string
          description: The retrieved content chunk
          example: "Humanoid robotics is a field that combines robotics and artificial intelligence..."
        score:
          type: number
          description: Similarity score between query and content
          minimum: 0.0
          maximum: 1.0
          example: 0.87
        metadata:
          type: object
          description: Metadata about the source
          properties:
            source:
              type: string
              description: Source document identifier
              example: "physical_ai_textbook_ch3.pdf"
            chapter:
              type: string
              description: Chapter identifier
              example: "Chapter 3"
            model:
              type: string
              description: Model identifier (if applicable)
              example: "Model 1"
            page:
              type: integer
              description: Page number in source
              example: 45
            section_title:
              type: string
              description: Title of the section
              example: "Fundamentals of Humanoid Movement"

    ErrorResponse:
      type: object
      required:
        - error
        - success
      properties:
        error:
          type: string
          description: Error message
          example: "Failed to connect to Qdrant database"
        success:
          type: boolean
          description: Whether the operation was successful
          example: false
        details:
          type: object
          description: Additional error details (optional)
          example: {"connection_timeout": 30}

    HealthResponse:
      type: object
      required:
        - status
        - success
      properties:
        status:
          type: string
          description: Overall health status
          enum: [healthy, degraded, unhealthy]
          example: "healthy"
        services:
          type: object
          description: Status of individual services
          properties:
            agent:
              type: string
              description: Agent service status
              enum: [up, down]
              example: "up"
            qdrant:
              type: string
              description: Qdrant connection status
              enum: [connected, disconnected]
              example: "connected"
        success:
          type: boolean
          description: Whether the health check was successful
          example: true