import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration to control the order
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI And Robotics Learning',
      items: ['Physical AI And Robotics Learning/intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Beginners Level',
      items: [
        'Beginners Level/create-a-page',
        'Beginners Level/create-a-document',
        'Beginners Level/create-a-blog-post',
        'Beginners Level/deploy-your-site',
        'Beginners Level/markdown-features',
        'Beginners Level/congratulations',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Intermediate Level',
      items: [
        'Intermediate Level/manage-docs-versions',
        'Intermediate Level/translate-your-site',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1',
      items: [{type: 'autogenerated', dirName: 'Module 1'}],
    },
    {
      type: 'category',
      label: 'Module 2',
      items: [{type: 'autogenerated', dirName: 'Module 2'}],
    },
    {
      type: 'category',
      label: 'Module 3',
      items: [{type: 'autogenerated', dirName: 'Module 3'}],
    },
    {
      type: 'category',
      label: 'Module 4',
      items: [{type: 'autogenerated', dirName: 'Module 4'}],
    },
  ],
};

export default sidebars;
